title: Hy-Souls Wiki
description: A Dark Souls-inspired mod for Hytale
theme: just-the-docs

url: ""

aux_links:
  "GitHub":
    - "https://github.com/CohesionForce/Hy-Souls"

nav_sort: order

heading_anchors: true

search_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Hy-Souls &mdash; A Dark Souls-inspired Hytale mod"
