title: Hy-Souls Wiki
description: A Dark Souls-inspired mod for Hytale
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: ""

aux_links:
  "GitHub":
    - "https://github.com/NOWHER3/Hy-Souls"

nav_sort: order

heading_anchors: true

search_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Hy-Souls &mdash; A Dark Souls-inspired Hytale mod"
